name: flutter_news_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  http: ^1.2.1
  intl: any
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_gen_runner: ^5.4.0 # dart run build_runner build
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  # icons_launcher: ^2.1.7 # dart run icons_launcher:create
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  
  
flutter_gen:
  output: lib/assets/
  line_length: 120
  integrations:
    flutter_svg: true

# icons_launcher:
#   image_path: ""
#   platforms:
#     macos:
#       enable: true
#     windows:
#       enable: true
#     linux:
#       enable: true
#     web:
#       enable: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
