name: flutter_news_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  desktop_window: ^0.4.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  http: ^1.2.1
  intl: any
  json_annotation: ^4.8.1
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  sqflite: ^2.3.3+1

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_gen_runner: ^5.4.0 # dart run build_runner build
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  icons_launcher: ^2.1.7 # dart run icons_launcher:create
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter_gen:
  output: lib/assets/
  line_length: 120
  integrations:
    flutter_svg: true

icons_launcher:
  image_path: "assets/images/AppIcon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
    web:
      enable: true

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Airstrike
      fonts:
        - asset: assets/fonts/air-strike/airstrike.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/montserrat/Montserrat-VariableFont_wght.ttf
